name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      publish:
        description: Publish Mode (release, snapshot, none)
        required: true
        default: "none"

jobs:
  build:
    strategy:
      matrix:
        java: [ 21 ]
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout Repository
          uses: actions/checkout@v4

      -   name: Setup Java ${{ matrix.java }}
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: ${{ matrix.java }}

      -   name: Setup Gradle
          uses: gradle/actions/setup-gradle@v4

      -   name: make gradle wrapper executable
          run: chmod +x ./gradlew

      -   name: Build
          run: ./gradlew build

      -   name: Capture build artifacts
          uses: actions/upload-artifact@v4
          with:
            name: Artifacts
            path: build/libs/

      -   name: Publish Release
          if: ${{ github.event.inputs.publish == 'release' }}
          run: ./gradlew publishAllPublicationsToDevOsReleasesRepository -PdevOsReleasesUsername=cichlidmc -PdevOsReleasesPassword="${{ secrets.DEVOS_PASS }}"

      -   name: Publish Snapshot
          if: ${{ github.event.inputs.publish == 'snapshot' }}
          run: ./gradlew publishAllPublicationsToDevOsSnapshotsRepository -PdevOsSnapshotsUsername=cichlidmc -PdevOsSnapshotsPassword="${{ secrets.DEVOS_PASS }}"
